### ISSUE TITLE
IRS will discontinue updates to the IRS 990 Filings dataset on AWS starting December 31, 2021

### ISSUE THREAD

**Issue by guidoiaquinti** [grantmakers/grantmakers.github.io#79]
I think this update will unfortunately impact this project:

> On December 16, 2021 the IRS announced that it would discontinue updates to the IRS 990 Filings dataset on AWS, starting December 31, 2021. The IRS has requested public inquiries be directed to +1-800-829-1040.Machine-readable data from certain electronic 990 forms filed with the IRS from 2013 to present.
> 
> ref: https://registry.opendata.aws/irs990/

**Comment by chadokruse** [comment]
Thanks for this @guidoiaquinti. Looks like the IRS has decided to move off AWS and self-host the files instead. We'll certainly miss the automation the S3 SDKs allowed for, but once the fetch scripts are updated to pull from the IRS site directly (instead of AWS), we should be good to go. 

I'll keep this Issue open to post progress and list any quirks I come across.

Thanks again for filing the Issue!

**Comment by chadokruse** [comment]
I'm going to go ahead and close this as there won't be any long term impact to the project. Thanks again for the heads up. For future visitors, the entire dataset is indeed openly available at IRS.gov.
